["(", "let", "x", "'testsym", ")", "(", "let", "y", "'(", "x", "1", "2", ")", ")"]
["let", "x", "'testsym"]
["let", "y", "'(", "x", "1", "2", ")"]
["quote", "x", "1", "2"]
[LExpression(@first=LSymbol(@name="let"), @arguments=[LSymbol(@name="x"), LSymbol(@name="'testsym")]), LExpression(@first=LSymbol(@name="let"), @arguments=[LSymbol(@name="y"), LList(@elems=[LSymbol(@name="x"), LNumber(@value=1), LNumber(@value=2)])])]
